In [1]:
def gcd(a,b):
    if b == 0:
        return a
    else:
        return gcd(b, a%b)

print(gcd(48,18))

6


In [2]:
def decimalToBinary(n):
    assert int(n) == n # "the parameter must be intger only "
    if n==0:
        return 0
    else:
        return n%2 + 10* decimalToBinary(int(n/2))


decimalToBinary(13)

1101

In [3]:
from array import *

arr1 = array("i", [1,2,3,4,5,6])
arr2 = array("d", [1.3,1.5,1.6])


print(arr2)

array('d', [1.3, 1.5, 1.6])


In [4]:
arr1.insert(2,0)

In [5]:
arr1

array('i', [1, 2, 0, 3, 4, 5, 6])

In [6]:
def traverseArray(array):
    for i in array:
        print(i)
    
traverseArray(arr1)

1
2
0
3
4
5
6


In [7]:
arr3 = array('i', [1, 2, 0, 3, 4, 5, 6])

arr3.remove(4)

In [8]:
arr3

array('i', [1, 2, 0, 3, 5, 6])

In [9]:
from array import *

my_array = array('i', [1,2,34,5,6,7])

for i in my_array:
    print(i)

1
2
34
5
6
7


In [10]:
my_array[2]

34

In [11]:
my_array.append(355)
my_array

array('i', [1, 2, 34, 5, 6, 7, 355])

In [12]:
my_array.insert(2,20)
my_array

array('i', [1, 2, 20, 34, 5, 6, 7, 355])

In [13]:
arr3 = array('i', [10, 20, 30, 33, 44, 55, 66])

In [14]:
my_array.extend(arr3)
my_array

array('i', [1, 2, 20, 34, 5, 6, 7, 355, 10, 20, 30, 33, 44, 55, 66])

In [15]:
tempList = [20,30,40]

my_array.fromlist(tempList)

my_array

array('i', [1, 2, 20, 34, 5, 6, 7, 355, 10, 20, 30, 33, 44, 55, 66, 20, 30, 40])

In [16]:
my_array.remove(20)

In [17]:
my_array

array('i', [1, 2, 34, 5, 6, 7, 355, 10, 20, 30, 33, 44, 55, 66, 20, 30, 40])

In [18]:
my_array.pop()

my_array

array('i', [1, 2, 34, 5, 6, 7, 355, 10, 20, 30, 33, 44, 55, 66, 20, 30])

In [19]:
import numpy as np

twoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
twoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
newtwoDArray = np.insert(twoDArray, 3 ,[11,12,13], axis = 0)
newtwoDArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [22]:
twoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
newtwoDArray = np.append(twoDArray, [[5,6,70]], axis = 0)

In [24]:
newtwoDArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 5,  6, 70]])

In [25]:
def accessElement(array, rowIndex, colIndex):
    if rowIndex >= len(array) or colIndex >= len(array[0]):
        print('Incorrect index')
        
    else:
        print(array[rowIndex][colIndex])
        
        
accessElement(newtwoDArray, 3,2)

70


In [26]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'T searchTDArray(array, value) '+str(i)+' '+str(j)
            
    return "The Element is not found"
print(searchTDArray(newtwoDArray, 777))

The Element is not found


In [27]:
print(newtwoDArray)
print("**********************")
newDArray = np.delete(newtwoDArray, 0 ,axis = 0)

print(newDArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  6 70]]
**********************
[[ 4  5  6]
 [ 7  8  9]
 [ 5  6 70]]


In [28]:
myList = [2,4,5,6,70,80]
def searchinList(list, value):
    for i in list:
        if i == value:
            return list.index(value)
    return "The value does not exist in the list"

print(searchinList(myList, 70))
        

4


In [29]:
total = 0
count = 0

while (True):
    inp = input("Enter a number: ")
    if inp == 'done' : break
    
    value = float(inp)
    total = total + value
    count = count + 1
    average = total / count
    
    
print("Average ", average)

Enter a number: 2
Enter a number: 23
Enter a number: 23
Enter a number: 23
Enter a number: done
Average  17.75


In [32]:
myList = []

while (True):
    inp = input("Enter the Number: ")
    if inp == "done" : break
        
    value = float(inp)
    myList.append(value)
    
average = sum(myList)/ len(myList)
    
print("Average", average)

Enter the Number: 1
Enter the Number: 34
Enter the Number: 43
Enter the Number: done
Average 26.0


In [33]:
a = 'spam spam spam'

b = a.split()
print(b)

['spam', 'spam', 'spam']


In [34]:
l1 =  [1,3,4,5]
l2 = l1
l3 = l1[:]
l3[0] = 10
l2[1] = 30

In [35]:
print(l1)
print(l2)
print(l3)

[1, 30, 4, 5]
[1, 30, 4, 5]
[10, 3, 4, 5]


In [36]:
numDays = int(input("how many days Temperature ?: "))
total = 0
temp = []
for i in range(1, numDays+1):
    nextday = int(input("Day " + str(i) + "'s high temp : "))
    temp.append(nextday)
    total += nextday
    
avg = round(total/numDays, 2)

count = 0
for j in temp:
    if j > avg:
        count +=1
print(count)
print("\nAverage = "+str(avg))

how many days Temperature ?: 


ValueError: invalid literal for int() with base 10: ''

In [37]:
mylist = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]



def findMissing(list, n):
    sum1 = n*(n+1)/2
    sum2 = sum(list)
    print(sum1-sum2)
    
findMissing(mylist, len(mylist)+1)

17.0


In [38]:
def findPairs(nums,target):
    for i in range(len(nums)):
        for j in range(i+1 , len(nums)):
            if nums[i] == nums[j]:
                continue
            elif nums[i] + nums[j] == target:
                print(nums[i],nums[j])
                
                
mylist = [1,2,3,4,5,6,7]

findPairs(mylist,9)

2 7
3 6
4 5


In [39]:
import numpy as np

myArray = np.array([1,2,3,4,5,6,7,8,9,10,21])

def findNumber(array, number):
    for i  in array:
        if i == number:
            return True
    else:
        return "Number not present"
    
findNumber(myArray, 17)

'Number not present'

In [40]:
def isUnique(list):
    a = []
    for i in list:
        if i in a:
            return False
        else: 
            a.append(i)
            
    return True

list = [1,2,34,55,34,55,65]
list1 = [1,2,3,4,5,6]
print(isUnique(list))
print(isUnique(list1))

False
True


In [41]:
def permutation(list1,list2):
    if len(list1) != len(list2):
        return False
    else:
        list1.sort()
        list2.sort()
        if list1 == list2:
            return True
        else:
            return False 
        
        
list1 = [1,2,3]
list2 = [1,3,1]

permutation(list1,list2)

False

In [42]:
import numpy as np

myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myArray)
print("**************")
def rotateMat(matrix):
    n = len(matrix)
    for layer in range(n//2):
        first = layer
        last = n-layer-1
        for i in range(first,last):
            top = matrix[layer][i]
            matrix[layer][i] = matrix[-i-1][layer]
            matrix[-i-1][layer] = matrix[-layer-1][-i-1]
            matrix[-layer-1][-i-1] = matrix[i][-layer-1]
            matrix[i][-layer-1] = top
    return matrix
    
 
print(rotateMat(myArray))
            
            

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [43]:
a = tuple('askaudhskfifjsdfikvnxcvuxjvjc sdfdfjfjkhfsuifjknvkjvjvv')
print(a)

('a', 's', 'k', 'a', 'u', 'd', 'h', 's', 'k', 'f', 'i', 'f', 'j', 's', 'd', 'f', 'i', 'k', 'v', 'n', 'x', 'c', 'v', 'u', 'x', 'j', 'v', 'j', 'c', ' ', 's', 'd', 'f', 'd', 'f', 'j', 'f', 'j', 'k', 'h', 'f', 's', 'u', 'i', 'f', 'j', 'k', 'n', 'v', 'k', 'j', 'v', 'j', 'v', 'v')


In [44]:
def searchTuple(p_tuple, element):
    for i in range(len(p_tuple)):
        if p_tuple[i] == element:
            return f"The {element} is tfound at {i} index"
    return "The element is not found"

newTuple = (2,3,4,5,67,20)

print(searchTuple(newTuple, 2))

The 2 is tfound at 0 index


In [45]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SlinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
        
        
singlyLinkedList = SlinkedList()
node1 = Node(1)
node2 = Node(2)

singlyLinkedList.head = node1
singlyLinkedList.head.next = node2
singlyLinkedList.tal = node2



In [46]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
        
    def insertSLL(self, value, location):
        newNode = Node(value)
        if self.head is None:
            self.head = newNode
            self.tail = newNode
        else:
            if location == 0:
                newNode.next = self.head
                self.head = newNode
            elif location == 1:
                newNode.next = None
                self.tail.next = newNode 
                self.tail = newNode
            else:
                tempNode = self.head
                index = 0
                while index < location-1:
                    tempNode = tempNode.next
                    index += 1
                nextNode = tempNode.next
                tempNode.next = newNode
                newNode.next = nextNode
                if tempNode == self.tail:
                    self.tail = newNode
                    
    
    
    
singlyLinkedList = SLinkedList()


singlyLinkedList.insertSLL(1,1)
singlyLinkedList.insertSLL(2,1)
singlyLinkedList.insertSLL(3,1)
singlyLinkedList.insertSLL(4,1)


singlyLinkedList.insertSLL(0,3)
print([node.value for node in singlyLinkedList])

[1, 2, 3, 0, 4]


In [47]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
        
    def insertSLL(self, value, location):
        newNode = Node(value)
        if self.head is None:
            self.head = newNode
            self.tail = newNode
        else:
            if location == 0:
                newNode.next = self.head
                self.head = newNode
            elif location == 1:
                newNode.next = None
                self.tail.next = newNode 
                self.tail = newNode
            else:
                tempNode = self.head
                index = 0
                while index < location-1:
                    tempNode = tempNode.next
                    index += 1
                nextNode = tempNode.next
                tempNode.next = newNode
                newNode.next = nextNode
                
                
                
    def traverseSLL(self):
        if self.head is None:
            print("The Singly Linked List does not exist")
            
        else:
            node = self.head
            while node is not None:
                print(node.value)
                node = node.next
                
                
                        
    
    
    
singlyLinkedList = SLinkedList()


singlyLinkedList.insertSLL(1,1)
singlyLinkedList.insertSLL(2,1)
singlyLinkedList.insertSLL(3,1)
singlyLinkedList.insertSLL(4,1)


singlyLinkedList.insertSLL(0,3)
print([node.value for node in singlyLinkedList])
singlyLinkedList.traverseSLL()

[1, 2, 3, 0, 4]
1
2
3
0
4


In [48]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
        
    def insertSLL(self, value, location):
        newNode = Node(value)
        if self.head is None:
            self.head = newNode
            self.tail = newNode
        else:
            if location == 0:
                newNode.next = self.head
                self.head = newNode
            elif location == 1:
                newNode.next = None
                self.tail.next = newNode 
                self.tail = newNode
            else:
                tempNode = self.head
                index = 0
                while index < location-1:
                    tempNode = tempNode.next
                    index += 1
                nextNode = tempNode.next
                tempNode.next = newNode
                newNode.next = nextNode
                
                
                
    def traverseSLL(self):
        if self.head is None:
            print("The Singly Linked List does not exist")
            
        else:
            node = self.head
            while node is not None:
                print(node.value)
                node = node.next
                
                
                        
    def searchSLL(self, nodeValue):
        if self.head is None:
            return "The list does not exist"
        else :
            node = self.head
            while node is not None:
                if node.value == nodeValue:
                    return node.value
                node = node.next
            return "The value does not exits in this list"
        
                
    
    
singlyLinkedList = SLinkedList()


singlyLinkedList.insertSLL(1,1)
singlyLinkedList.insertSLL(2,1)
singlyLinkedList.insertSLL(3,1)
singlyLinkedList.insertSLL(4,1)


singlyLinkedList.insertSLL(0,3)
# print([node.value for node in singlyLinkedList])
# singlyLinkedList.traverseSLL()

print(singlyLinkedList.searchSLL(3))

3


In [49]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
        
    def insertSLL(self, value, location):
        newNode = Node(value)
        if self.head is None:
            self.head = newNode
            self.tail = newNode
        else:
            if location == 0:
                newNode.next = self.head
                self.head = newNode
            elif location == 1:
                newNode.next = None
                self.tail.next = newNode 
                self.tail = newNode
            else:
                tempNode = self.head
                index = 0
                while index < location-1:
                    tempNode = tempNode.next
                    index += 1
                nextNode = tempNode.next
                tempNode.next = newNode
                newNode.next = nextNode
                
                
                
    def traverseSLL(self):
        if self.head is None:
            print("The Singly Linked List does not exist")
            
        else:
            node = self.head
            while node is not None:
                print(node.value)
                node = node.next
                
                
                        
    def searchSLL(self, nodeValue):
        if self.head is None:
            return "The list does not exist"
        else :
            node = self.head
            while node is not None:
                if node.value == nodeValue:
                    return node.value
                node = node.next
            return "The value does not exits in this list"
        
                

    def deleteNode(self, location):
        if self.head is Node:
            print("The SLL does not exits")
        else:
            if location == 0:
                if self.head == self.tail:
                    self.head = None
                    self.tail = None
                
                else:
                    self.head = self.head.next
            elif location == 1 :
                if self.head == self.tail:
                    self.head = None
                    self.tail = None
                else: 
                    node = self.head
                    while node is not None:
                        if node.next == self.tail:
                            break
                        node = node.next
                    node.next = None
                    self.tail = node
            else:
                tempNode = self.head
                index = 0
                while index < location -1 :
                    tempNode = tempNode.next
                    index +=1
                nextNode = tempNode.next
                tempNode.next = nextNode.next
                
                
            
            
            
            
    
singlyLinkedList = SLinkedList()


singlyLinkedList.insertSLL(1,1)
singlyLinkedList.insertSLL(2,1)
singlyLinkedList.insertSLL(3,1)
singlyLinkedList.insertSLL(4,1)


singlyLinkedList.insertSLL(0,3)
print([node.value for node in singlyLinkedList])
singlyLinkedList.traverseSLL()

print(singlyLinkedList.deleteNode(1))
print([node.value for node in singlyLinkedList])

[1, 2, 3, 0, 4]
1
2
3
0
4
None
[1, 2, 3, 0]


In [50]:
class Node:
    def __init__(self, value= None):
        self.value = value
        self.next = None
        
class SLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def __iter__(self):
        node = self.head
        while node:
            yield node
            node = node.next
        
    def insertSLL(self, value, location):
        newNode = Node(value)
        if self.head is None:
            self.head = newNode
            self.tail = newNode
        else:
            if location == 0:
                newNode.next = self.head
                self.head = newNode
            elif location == 1:
                newNode.next = None
                self.tail.next = newNode 
                self.tail = newNode
            else:
                tempNode = self.head
                index = 0
                while index < location-1:
                    tempNode = tempNode.next
                    index += 1
                nextNode = tempNode.next
                tempNode.next = newNode
                newNode.next = nextNode
                
                
                
    def traverseSLL(self):
        if self.head is None:
            print("The Singly Linked List does not exist")
            
        else:
            node = self.head
            while node is not None:
                print(node.value)
                node = node.next
                
                
                        
    def searchSLL(self, nodeValue):
        if self.head is None:
            return "The list does not exist"
        else :
            node = self.head
            while node is not None:
                if node.value == nodeValue:
                    return node.value
                node = node.next
            return "The value does not exits in this list"
        
                

    def deleteNode(self, location):
        if self.head is Node:
            print("The SLL does not exits")
        else:
            if location == 0:
                if self.head == self.tail:
                    self.head = None
                    self.tail = None
                
                else:
                    self.head = self.head.next
            elif location == 1 :
                if self.head == self.tail:
                    self.head = None
                    self.tail = None
                else: 
                    node = self.head
                    while node is not None:
                        if node.next == self.tail:
                            break
                        node = node.next
                    node.next = None
                    self.tail = node
            else:
                tempNode = self.head
                index = 0
                while index < location -1 :
                    tempNode = tempNode.next
                    index +=1
                nextNode = tempNode.next
                tempNode.next = nextNode.next
                
                
            
    
    def deleteEntireSLL(self):
        
        if self.head is None:
            print('The SLL does not exist')
        else:
            self.head = None
            self.tail = None
            
            
    
singlyLinkedList = SLinkedList()


singlyLinkedList.insertSLL(1,1)
singlyLinkedList.insertSLL(2,1)
singlyLinkedList.insertSLL(3,1)
singlyLinkedList.insertSLL(4,1)


singlyLinkedList.insertSLL(0,3)
print([node.value for node in singlyLinkedList])
singlyLinkedList.traverseSLL()

print(singlyLinkedList.deleteEntireSLL())

print([node.value for node in singlyLinkedList])

[1, 2, 3, 0, 4]
1
2
3
0
4
None
[]
